version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: StorageDb
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password      
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  storage_microservice:
    build:
      context: .
      dockerfile: Core/StorageMicroservice.API/Dockerfile
    container_name: storage_microservice
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "5000:8080"
      - "50416:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://mongo:27017
      - EventBus__Host=rabbitmq

volumes:
  mongo_data:
